### ISSUE TITLE
Minor Map Edits

### ISSUE THREAD

**Issue by inkenbrandt** [UGS-GIO/LakeBonnevilleSM#18]
Rosemary sent me the following:

> Hey Paul, I passed that Story Map on to my niece and nephew and they noticed a couple things I think are worth telling you. 
> 
> First, when they zoomed in to the photo location in the Stansbury section, the lake level polygon changed to the Bonneville polygon I think. So when they zoomed out, it was way bigger than it should have been. That "zoom in" link might be referencing the wrong map or if it's referencing the same map as other sections of the story map, it might need it's own to be created. I'm pretty sure you know your way around AGOL, but let me know if you need help sorting it out.
> 
> Second, the historical measurements of Great Salt Lake image later in the Story Map (GSL levels section) is not showing up as a thumbnail or when you enlarge it.

**Comment by Mackenzie-Cope** [comment]
Fixed the first issue. The Bonneville layer was on and showing instead of the Stansbury layer.

@inkenbrandt Do you remember what graph image was supposed to show up there? I went to the reference in the caption (https://waterdata.usgs.gov/ut/nwis/uv?site_no=10010000) and it looks like you can customize what you want the graph to show. From the text in that section, we may have been showing 1984 to present?

**Comment by inkenbrandt** [comment]
I would like to show the period of record:
https://waterdata.usgs.gov/nwis/dv?cb_62614=on&format=gif_default&site_no=10010000&referred_module=sw&period=&begin_date=1847-10-18&end_date=2021-06-15

**Comment by Mackenzie-Cope** [comment]
I added in the image Paul linked to and made sure both issues have been fixed. Paul took a look as well.
